In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset = pd.read_csv('Data1.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Belgium' 34.0 56000.0]
 ['Norway' nan 60000.0]
 ['Italy' 42.0 70000.0]
 ['France' 38.0 61000.0]
 ['Spain' 28.0 49000.0]
 ['Spain' nan 61000.0]
 ['Germany' nan 78000.0]
 ['France' 40.0 nan]
 ['Belgium' 34.0 nan]
 ['Norway' 30.0 54000.0]]


In [8]:
dataset = pd.read_csv('Data1.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [10]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 62529.41176470588]
 ['France' 35.0 58000.0]
 ['Spain' 37.1875 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Belgium' 34.0 56000.0]
 ['Norway' 37.1875 60000.0]
 ['Italy' 42.0 70000.0]
 ['France' 38.0 61000.0]
 ['Spain' 28.0 49000.0]
 ['Spain' 37.1875 61000.0]
 ['Germany' 37.1875 78000.0]
 ['France' 40.0 62529.41176470588]
 ['Belgium' 34.0 62529.41176470588]
 ['Norway' 30.0 54000.0]]


In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [13]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 0 1 0]


In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [15]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 28.0 49000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 40.0 62529.41176470588]
 [0.0 1.0 0.0 0.0 0.0 0.0 40.0 62529.41176470588]
 [0.0 1.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 34.0 62529.41176470588]
 [0.0 1.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 37.1875 61000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 42.0 70000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 37.1875 60000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 35.0 58000.0]]


In [16]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 37.1875 78000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 37.1875 52000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 34.0 56000.0]]


In [17]:
print(y_train)

[0 0 1 0 1 1 1 0 0 1 1 0 0 0 1 1]


In [18]:
print(y_test)

[0 1 0 1]


In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

In [20]:
print(x_train)


[[0.0 0.0 1.0 -0.2581988897471611 -0.3779644730092272
  -0.48038446141526137 -1.1308961050591904 -0.9239763845971212]
 [0.0 0.0 0.0 -0.2581988897471611 -0.3779644730092272 2.0816659994661326
  -1.4392128280572232 -1.4535203723982524]
 [0.0 0.0 1.0 -0.2581988897471611 -0.3779644730092272
  -0.48038446141526137 0.4106875099309733 -0.020636640701074037]
 [0.0 1.0 0.0 -0.2581988897471611 -0.3779644730092272
  -0.48038446141526137 0.4106875099309733 -0.020636640701074037]
 [0.0 1.0 0.0 -0.2581988897471611 -0.3779644730092272
  -0.48038446141526137 1.6439544019231043 1.7237435544085347]
 [0.0 0.0 0.0 -0.2581988897471611 -0.3779644730092272 2.0816659994661326
  -1.5933711895562397 -1.5594291699584786]
 [0.0 1.0 0.0 -0.2581988897471611 -0.3779644730092272
  -0.48038446141526137 0.10237078693294056 -0.18261480167553754]
 [0.0 1.0 0.0 -0.2581988897471611 -0.3779644730092272
  -0.48038446141526137 1.0273209559270389 0.982381971486951]
 [0.0 0.0 0.0 -0.2581988897471611 2.6457513110645903 -0.480384